### ISSUE TITLE
Incompatible Graphviz version

### ISSUE THREAD

**Issue by freshollie** [dstockhammer/docker-plantuml#18]
The [FAQ says](https://plantuml.com/en/faq) the following on the subject:

> The following version have been tested, and are known to work:
> - 2.26.3
> - 2.28
> - 2.30.1
> - 2.34
> - 2.36
> - 2.38
> - 2.44
> 
> Note that versions 2.39 to 2.42 do not work very well with PlantUML.

With the wrong Graphviz versions our diagrams are being generated with different padding than expected

**Comment by freshollie** [comment]
Further reading: https://forum.plantuml.net/11323/diagrams-on-docker-different-to-plantuml-com

**Comment by dstockhammer** [comment]
Thanks for reporting this, I wasn't aware of the issue. I'll try to find a good way to upgrade graphviz with minimal changes to the image otherwise.

**Comment by dstockhammer** [comment]
upgraded graphviz to `2.43.0` in [1.2021.10](https://github.com/dstockhammer/docker-plantuml/releases/tag/1.2021.10)
